connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql://db/dhis
connection.username = dhis
connection.password = dhis

system.update_notifications_enabled = 0ff

# Disable hibernate second-level cache (this config has no effect due to
# org.hisp.dhis.config.HibernateConfig; only code change dhis2/core-dev:42.0-local-no-cache actually
# turns it off)
hibernate.cache.use_second_level_cache = false
hibernate.cache.use_query_cache = false
hibernate.cache.region.factory_class = org.hibernate.cache.internal.NoCachingRegionFactory
# Disable org.hisp.dhis.cache (this config has no effect due to some intertwined logic in the
# ExtendedCacheBuilder)
system.cache.max_size.factor = 0

# TODO how to only add these for profile monitoring? or profile?
hibernate.generate_statistics = true

# Enable monitoring metrics
monitoring.hibernate.enabled = on
monitoring.ehcache.enabled = on
monitoring.jvm.enabled = on
monitoring.dbpool.enabled = on
monitoring.api.enabled = on
monitoring.uptime.enabled = on
monitoring.cpu.enabled = on

tracker.import.preheat.cache.enabled = off
