connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql://db/dhis
connection.username = dhis
connection.password = dhis

system.update_notifications_enabled = 0ff

# Enable second-level cache for EhCache metrics
hibernate.cache.use_second_level_cache = true
hibernate.cache.use_query_cache = true

# Enable monitoring metrics
monitoring.hibernate.enabled = on
monitoring.ehcache.enabled = on
monitoring.jvm.enabled = on
monitoring.dbpool.enabled = on
monitoring.api.enabled = on
monitoring.uptime.enabled = on
monitoring.cpu.enabled = on

tracker.import.preheat.cache.enabled = off
