ARG POSTGRES_BASE_IMAGE=postgis/postgis:13-3.5
ARG DHIS2_DB_DUMP_URL=https://databases.dhis2.org/sierra-leone/2.42.0/dhis2-db-sierra-leone.sql.gz

FROM busybox as downloader
ARG DHIS2_DB_DUMP_URL
WORKDIR /tmp
RUN wget --output-document dump.sql.gz "$DHIS2_DB_DUMP_URL"

FROM ${POSTGRES_BASE_IMAGE} as initializer

ENV POSTGRES_USER=dhis \
    POSTGRES_DB=dhis \
    POSTGRES_PASSWORD=dhis \
    PGUSER=dhis \
    PGDATABASE=dhis \
    PGPASSWORD=dhis

COPY --from=downloader /tmp/dump.sql.gz /docker-entrypoint-initdb.d/

RUN docker-entrypoint.sh postgres & \
    sleep 5 && \
    until psql --quiet --host=127.0.0.1 --port=5432 --set=application_name=docker --command "SELECT 'ok'" > /dev/null 2>&1; do sleep 1; done && \
    su postgres -c 'pg_ctl stop --pgdata="$PGDATA" --mode=fast'

FROM ${POSTGRES_BASE_IMAGE}

ENV POSTGRES_USER=dhis \
    POSTGRES_DB=dhis \
    POSTGRES_PASSWORD=dhis \
    PGUSER=dhis \
    PGDATABASE=dhis \
    PGPASSWORD=dhis

COPY --from=initializer /var/lib/postgresql/data /var/lib/postgresql/data

CMD ["postgres", "--config-file=/etc/postgresql.conf"]